# Generated by Django 5.1.6 on 2025-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
