# Generated by Django 5.1.6 on 2025-02-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
