# Generated by Django 5.1.6 on 2025-02-20 09:43

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_checkout_alter_order_order_no_and_more'),
        ('seller', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dark_store',
            field=models.ForeignKey(default=orders.models.get_initial, on_delete=django.db.models.deletion.CASCADE, to='seller.dark_store'),
        ),
    ]
