# Generated by Django 5.1.6 on 2025-02-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('subcategory', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product_subcategory')),
            ],
        ),
    ]
