# Generated by Django 5.1.6 on 2025-02-15 12:03

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=products.models.get_default_subcategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product_subcategory'),
        ),
    ]
